### PR TITLE
Re definitions - removed config.h

### PR DESCRIPTION
**Pull request by thobbsinteractive**

### CODE REVIEW

**Review by GrimSqueaker — APPROVED** [review]
Seems all ok by me. I could also compile and play the first level

**Comment by turican0** [comment]
Hi Sebastian, can merge Tim and my branches? I wait for it now. Until then, I don't want to make major changes to the code.

Thank you, Tom.

**Comment by GrimSqueaker** [comment]
Ok, let's merge this and then I'll directly merge this into my dev branch.

**Comment by GrimSqueaker** [comment]
Hi,
I have merged both your dev branches into my dev, so you can merge back and we are all in sync again. Yesterday I have also moved my stable branch a bit forward, too.

**Pull request merged**
