### PR TITLE
Sync

### PR DESCRIPTION
**Pull request by GrimSqueaker**
Fixes, changes by @turican0, sonar cloud only in @thobbsinteractive fork, first unit tests, some 64 bit preparations

### CODE REVIEW

**Comment by GrimSqueaker** [comment]
Hmmm, looks like I broke sonarcloud

**Review by thobbsinteractive — COMMENTED** [review]
There are over 4k new files here. 
Most seem to be in x64/debug/TMAPS, are these accidentally left uncompressed? are they duplicates or were they really meant to be included?

**Comment by GrimSqueaker** [comment]
> There are over 4k new files here.
> Most seem to be in x64/debug/TMAPS, are these accidentally left uncompressed? are they duplicates or were they really meant to be included?

This is a build directory for VS from @turican0. For the moment I did not care, because there are redundant files already in a few places already.
I think this is something for you on Windows to decide on if you and @turican0 could add the build directories to the .gitignore file and have a custom step in the VS solution copy all necessary files to the build directory so that you can start the game there. AFAIK there are post-build steps possible to implement in VS.
On Linux this is taken care of by CMake.

**Comment by GrimSqueaker** [comment]
I think we should have one common place to put the assets like biggraphics and a config.ini template. And from there the build system copies it into the build/install directory (CMake provides an install step after the build which allows to separate files that are needed to run the application from intermediate build artefacts like .o files).

**Comment by thobbsinteractive** [comment]
Yeah I'll take a look and see what can be configured/excluded tomorrow

**Comment by GrimSqueaker** [comment]
Thanks :-)

**Comment by thobbsinteractive** [comment]
> I think we should have one common place to put the assets like biggraphics and a config.ini template. And from there the build system copies it into the build/install directory (CMake provides an install step after the build which allows to separate files that are needed to run the application from intermediate build artefacts like .o files).

Actually I can move it to the main directory and use ".../" to reference it in the ini file. its an easy fix. I will try it, we can always revert

**Comment by thobbsinteractive** [comment]
> Thanks :-)

I will try and add a copy of the graphics and sound stuff to the CMake. Luckily they are not essential to run the game

**Comment by thobbsinteractive** [comment]
Everything is running well but we have a bug with the Sprite culling. If you tilt the camera sprites towards the top of the screen begin disappear. I am pretty sure this is new in the build

**Comment by GrimSqueaker** [comment]
> @GrimSqueaker
> Everything is running well but we have a bug with the Sprite culling. If you tilt the camera sprites towards the top of the screen begin disappear. I am pretty sure this is new in the build. Can you take a quick look to see if its anything obvious that has changed?
> I will still merge this, but will raise an issue if you cannot find the cause.

Yes, I think I can reproduce this in this merge and it was working on your current dev branch. Maybe later I can do a binary search for the commit that introduced the regression. @turican0, what do you think? You know the code best and might directly have an idea what has changed.

**Comment by GrimSqueaker** [comment]
I have opened an issue for this https://github.com/GrimSqueaker/remc2/issues/45

**Comment by thobbsinteractive** [comment]
Thanks. I have merged in your dev branch.

**Pull request merged**
